variables:
  DOCKER_IMAGE: ${DOCKER_REGISTRY}/wert2all/cv/cicd:latest

stages:
  - docker
  - dependencies
  - test
  - build
  - deploy

prepare_docker_image:
  stage: docker
  tags:
    - docker-push
  script:
    - docker build ./ -f infra/Dockerfile -t ${DOCKER_IMAGE}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD wert2all.nsupdate.info:5050
    - docker push ${DOCKER_IMAGE}

install_dependencies:
  image: $DOCKER_IMAGE
  stage: dependencies
  needs:
    - 'prepare_docker_image'
  tags:
    - docker
  script:
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules

lint:commit:
  image: $DOCKER_IMAGE
  stage: test
  needs:
    - 'install_dependencies'
  tags:
    - docker
  script:
    - pnpm lint:commit
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
    policy: pull

lint:ng:
  image: $DOCKER_IMAGE
  stage: test
  needs:
    - 'install_dependencies'
  tags:
    - docker
  script:
    - pnpm lint:ng
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
    policy: pull

lint:css:
  image: $DOCKER_IMAGE
  stage: test
  needs:
    - 'install_dependencies'
  tags:
    - docker
  script:
    - pnpm lint:css
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
    policy: pull

build:
  image: $DOCKER_IMAGE
  stage: build
  needs:
    - 'install_dependencies'
  tags:
    - docker
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - rm ./src/environments/environment.ts
    - cp .secure_files/environment.production.ts ./src/environments/environment.ts
    - pnpm build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
      - dist
    policy: pull
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist

deploy:
  stage: deploy
  image: $DOCKER_IMAGE
  tags:
    - deploy
  needs:
    - 'build'
  script:
    - ls -al dist/cv
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -rzh ./dist/cv/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH --delete-after --delete

  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
      - dist
    policy: pull
  only:
    - main
